server:
  port: 8999
  servlet:
    context-path: /iban-svc/api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /iban-web-ui.html
    operationsSorter: method
spring:
  application:
    name: iban-svc
  logging:
    level:
      sa.com.saib.enterprise.iban: INFO
      org.springframework.web: INFO
      org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/sbdatajdbc
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true